"""empty message

Revision ID: c5aef7559e47
Revises: e5846a0463a2
Create Date: 2021-04-19 15:30:04.056729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5aef7559e47'
down_revision = 'e5846a0463a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('phone', table_name='base_model')
    op.drop_index('username', table_name='base_model')
    op.drop_table('base_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time', mysql.DATETIME(), nullable=True),
    sa.Column('type_name', mysql.VARCHAR(collation='utf8mb4_bin', length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_bin', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_bin', length=11), nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_bin', length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'base_model', ['username'], unique=True)
    op.create_index('phone', 'base_model', ['phone'], unique=True)
    op.drop_table('news_type')
    # ### end Alembic commands ###
